## Лабораторная работа №1

In [2]:
import numpy as np

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [11]:
# 1
a = np.loadtxt('C:\\Users\\1\\Documents\\minutes_n_ingredients.csv',  dtype='int32', delimiter=',', skiprows=1)
a[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

In [44]:
# 2
np.mean(a[:, 1:3], axis=0)

array([2.16010065e+04, 9.01703000e+00])

In [45]:
np.min(a[:, 1:3], axis=0)

array([1, 1])

In [46]:
np.max(a[:, 1:3], axis=0)

array([2147483647,         39])

In [47]:
np.median(a[:, 1:3], axis=0)

array([40.,  9.])

In [12]:
# 3
np.quantile(a[:, 1], 0.75)

65.0

In [9]:
# 4
a[a[:, 1] == 0] = 1

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

In [12]:
# 5
len(np.unique(a[:, 0]))

100000

In [19]:
# 6
np.unique(a[:, 2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

In [23]:
# 7
b = a[a[:, 2] < 5]
b

array([[204134,      5,      3],
       [ 25623,      6,      4],
       [484223,     18,      4],
       ...,
       [227056,     30,      4],
       [128811,     15,      4],
       [370915,      5,      4]])

In [16]:
# 8
c = a[:, 1]/a[:, 2]
np.max(c)

268435455.875

In [27]:
# 9
s_a = np.argsort(a[:, 1])
i_a = s_a[-100:] #Индексы топа 100

# top = a[:, 1][i_a]

np.mean(a[:, 2][i_a])

6.61

In [41]:
# 10

n = 10
index = np.random.choice(a.shape[0], n)
a_random = a[index]
a_random

array([[ 75675,     45,      7],
       [148769,    275,     11],
       [187995,     55,      8],
       [512305,     35,     14],
       [336455,     45,      6],
       [196101,     15,      5],
       [474359,    110,     19],
       [318428,     45,      9],
       [ 66982,     40,      8],
       [370205,     30,      9]])

In [19]:
# 11

q = len(a[a[:, 2] < np.mean(a[:, 2])]) #количество ингредиентов меньше среднего
q / (len(a) / 100)

58.802

In [7]:
# 12
# a2 = np.where((a[:, 1] <= 20) & (a[:, 2] <= 5))

a2 = np.c_[a, (a[:, 1] < 20) & (a[:,2] < 5)]
a2

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [84]:
# 13
a2 = a[np.where((a[:, 1] <= 20) & (a[:, 2] <= 5))]
np.size(a2) / (np.size(a) / 100)

9.943

In [91]:
# 14

a_short = a[np.where(a[:, 1] < 10)]
a_norm = a[np.where((a[:, 1] > 10) & (a[:, 1] < 20))]
a_long = a[np.where(a[:, 1] >= 20)]

In [108]:
short_col = np.array([0 for i in range(len(a_short))])
short_col = short_col.reshape(len(short_col), 1)

norm_col = np.array([1 for i in range(len(a_norm))])
norm_col = norm_col.reshape(len(norm_col), 1)

long_col = np.array([2 for i in range(len(a_long))])
long_col = long_col.reshape(len(long_col), 1)

In [114]:
a_short = np.append(a_short, short_col, axis=1)
a_norm = np.append(a_norm, norm_col, axis=1)
a_long = np.append(a_long, long_col, axis=1)

#?